In [1]:
import requests
import pandas as pd
import numpy as np

In [2]:
url= "https://basketball.realgm.com/ncaa/team-stats#:%7E:text=2021-2022%20NCAA%20Averages%20-%20Team%20Totals%20%20,%20%2083.8%20%2014%20more%20rows%20"

In [3]:
tables = pd.read_html(url)
len(tables)

1

In [4]:
df= tables[0]
df.head()

,#,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
0,1,Gonzaga,31,39.9,87.8,32.9,62.6,0.526,8.3,22.2,...,19.2,0.712,9.2,31.2,40.4,18.4,6.5,5.8,11.4,15.5
1,2,South Dakota State,35,40.2,85.9,30.8,59.1,0.521,9.3,20.9,...,19.7,0.758,7.1,27.3,34.4,15.1,6.1,2.5,11.0,15.3
2,3,Arizona,36,40.2,84.6,30.5,61.5,0.496,7.8,22.0,...,21.4,0.739,11.0,29.3,40.3,19.8,6.7,5.8,13.4,16.6
3,4,Oral Roberts,31,40.3,83.3,30.2,66.2,0.456,11.6,30.6,...,15.4,0.730,10.3,28.6,38.9,11.7,5.5,4.2,9.9,15.4
4,5,Iowa,36,40.2,83.2,29.8,64.5,0.461,9.2,25.3,...,19.4,0.749,11.2,24.5,35.7,16.0,7.3,4.3,9.2,16.2

In [ ]:
df.to_csv("Teams.csv")